site_name: betterstack Documentation
theme: material
nav:
  - Головна: README.md
  - API Документація:
    - Контракт API: api-contract.md
  - CI/CD та DoD:
    - CI/CD Pipeline: ci-cd-and-dod/ci-cd-docs.md
    - Definition of Done: ci-cd-and-dod/definition-of-done.md
  - Архітектура:
    - System Specification (SSD): architecture/SSD.md
    - Software Design (SDD): architecture/SDD.md
    - Infrastructure (ISD): architecture/ISD.md
  - Забезпечення якості:
    - Test Strategy: quality/test-strategy.md
    - Traceability Matrix: quality/traceability-matrix.md